version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=LkbxGUp0CVL6561rWIpGFMnzDrFQaatGPlzRWUDI
      - ZONE=kkumaresan.com
